kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      name: http
      port: 8005
      targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: "{{ .Release.Name }}-{{ .Chart.Name }}"
          image: "{{ .Values.registry }}/{{ .Values.repository }}/{{ .Values.image }}:{{ .Chart.AppVersion }}"
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--host=0.0.0.0"
            - "--port=8005"
            - "--log-level=info"
            - "--log-config=uvicorn_config.json"
          ports:
            - containerPort: 8005
          imagePullPolicy: Always
          env:
            - name: ELASTICSEARCH_SERVICE_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: atop-globe-config
                  key: elasticsearch_service_hosts
