kind: Service
apiVersion: v1
metadata:
  name: analysis
  labels:
    app: analysis
spec:
  selector:
    app: analysis
  ports:
    - protocol: TCP
      name: http
      port: 8005
      targetPort: 8005
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
  labels:
    app: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: analysis
          image: {{ .Values.image }}
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--reload"
            - "--host=0.0.0.0"
            - "--port=8005"
          ports:
            - containerPort: 8005
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: ELASTICSEARCH_SERVICE_HOSTS
              value: {{ .Values.elasticsearch_service_hosts }}
