import os


ELASTICSEARCH_SERVICE_HOSTS = os.getenv('ELASTICSEARCH_SERVICE_HOSTS')
KS_SERVICE_HOSTS = os.getenv('KS_SERVICE_HOSTS')
KS_SERVICE_USER = os.getenv('KS_SERVICE_USER')
KS_SERVICE_PWD = os.getenv('KS_SERVICE_PWD')
NAMESPACE = os.getenv('NAMESPACE')
